### ISSUE TITLE
[SUGGESTION] Add the message link to the quote

### ISSUE THREAD

**Issue by wolfieboy09** [DaRealTurtyWurty/SuperTurtyBot#260]
When you get a quote, it gets you this:
![image](https://github.com/user-attachments/assets/ddeaa84e-d124-4b50-8b17-ba180762ad23)

It tells you who added it, who said it, and the timestamp. This suggestion requests the ability to link the message in the embed so you can see the context

**Comment by DaRealTurtyWurty** [comment]
Currently this is impossible with how the quotes were implemented, and so this wouldn't work retroactively without manually adding the correct data.

For new quotes, its certainly possible to do this though, since quotes have to be taken from a particular message, and can't be made up, so its worth considering.

**Comment by O7410** [comment]
I have nothing better to do, so here's a list of quote number to message link
[messagelinks.txt](https://github.com/user-attachments/files/17463737/messagelinks.txt)
The ones that are empty I couldn't find, probably deleted

**Comment by DaRealTurtyWurty** [comment]
Fixed by 9d68399d22d83db96c47e8f89484d349756c6f09
